# Generated by Django 3.2.3 on 2022-05-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('health', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('moisture', models.CharField(max_length=200)),
                ('nitrogen', models.CharField(max_length=200)),
                ('phosphorus', models.CharField(max_length=200)),
                ('potassium', models.CharField(max_length=200)),
            ],
        ),
    ]
